version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/usr/src/app
    ports:
      - "5000:5000"
    command: ['python', '-u', 'generate.py', '284']
